### ISSUE TITLE
Only up to 10 waveforms are loaded from a saved scope session

### ISSUE THREAD

**Issue by miek** [azonenberg/scopehal-apps#108]
It looks like the `HistoryWindow`'s max waveforms is not changed from the default of 10 before replaying history on load, so any extra waveforms get dropped.

**Comment by azonenberg** [comment]
Correct. While we don't explicitly store the number of waveforms in the save file, the number of child nodes under the "waveforms:" node in the scope_metadata.yml file is sufficient for loading.

The logic that loads the waveforms should call HistoryWindow::SetMaxWaveforms() appropriately before actually adding the saved waveforms to the history.
