### ISSUE TITLE
Add "about" dialog

### ISSUE THREAD

**Issue by azonenberg** [azonenberg/scopehal-apps#175]

**Comment by tarunik** [comment]
<azonenberg> as far as content it should display the following (I'm not picky on formatting for now)...
<azonenberg> * copyright 2012-2020 me
<azonenberg> * BSD license (either as text or just a mention "3-clause BSD license" or similar)
<azonenberg> * list of contributors, put github usernames to start and then we can replace those with real names on request
<azonenberg> * version 0.1
<azonenberg> * git hash (this will need some cmake integration probably)
