### ISSUE TITLE
Window title of protocol analyzer windows not shown or imcomplete

### ISSUE THREAD

**Issue by electroniceel** [azonenberg/scopehal-apps#215]
On some linux window managers (or desktop environments, not sure) the window title of protocol analyzer windows is not shown at all, on some it is missing things like the "X" to close or the title or correct colors/style.

I tested these desktop environments with their default window managers:
KDE: incomplete
Xfce: correctly shown, "X" to close works
awesome: complete title block missing
Cinnamon: complete title block missing

All tests were done with Fedora 32, x86_64, X.org, AMD GPU.

This problem was also seen by user bluecmd[m]1 when running glscopeclient in WSL: https://www.youtube.com/watch?v=E6XVPqGP0gA

Screenshot from KDE:
![Screenshot_20201004_225852](https://user-images.githubusercontent.com/1341614/95137677-e7177700-0768-11eb-994d-d79f3306f43e.png)

**Comment by nshcat** [comment]
I can reproduce and confirm this, on my Linux laptop with awesomeWM, the title block is missing.

**Comment by azonenberg** [comment]
Please test and see if 361221f fixes it.

**Comment by nshcat** [comment]
The linked commit indeed fixes the issue for AwesomeWM.

**Comment by azonenberg** [comment]
Seems like everyone affected has confirmed the fix. Closing.

**Comment by electroniceel** [comment]
Fixed for me on KDE too
