### ISSUE TITLE
Figure out CMake libgl/libglvnd warning

### ISSUE THREAD

**Issue by azonenberg** [azonenberg/scopehal-apps#230]
Do we want to switch to using glvnd on Linux? do we need to do anything special in our application or can we just silently swap it in?

Need to look into this.

**Comment by nshcat** [comment]
```
if (POLICY CMP0072)
    cmake_policy (SET CMP0072 x)
endif(POLICY CMP0072)
```
Where x is either OLD or NEW. NEW will use GLVND.

**Comment by azonenberg** [comment]
Yeah it's more a question of testing GLVND on a couple of platforms and making sure it works properly.
