### ISSUE TITLE
"Connect to Instrument" dialog doesn't have a default button set

### ISSUE THREAD

**Issue by whitequark** [azonenberg/scopehal-apps#256]
So I can't hit Enter in the last field to accept the values. Also there seems to be no padding between fields so it looks ugly, though this is minor.

**Comment by nshcat** [comment]
Should be fixed now. Please reopen if the issue persists for you.

**Comment by whitequark** [comment]
Confirmed as fixed.

**Comment by whitequark** [comment]
> Please reopen

I actually couldn't do that if I needed (there is no "reopen" button for me).

![Screenshot_20201027_163045](https://user-images.githubusercontent.com/54771/97331876-c32fe880-1871-11eb-9c5c-e2725abf2aae.png)

**Comment by nshcat** [comment]
Huh, that's interesting. I'll keep future issues open until they're confirmed fixed.
