### ISSUE TITLE
Fonts should respect GDK_DPI_SCALE

### ISSUE THREAD

**Issue by whitequark** [azonenberg/scopehal-apps#257]
You probably want to use `gtkWindow.get_screen()->get_resolution();` for that.

**Comment by azonenberg** [comment]
@whitequark I think this is fixed, please confirm and close?

**Comment by whitequark** [comment]
> please confirm and close?

Cannot confirm, trigger still not movable at GDK_SCALE=2.

**Comment by azonenberg** [comment]
This issue is only for text displaying too small and not respecting DPI scaling. #255 is the ticket for mouse input not being correctly scaled, which is a separate bug.

If rendering is now appropriately scaled, even if input isn't working, this issue can be closed.

**Comment by azonenberg** [comment]
Confirmed fixed.
