### ISSUE TITLE
glscopeclient fails to run under Wayland due to GLEW init failure

### ISSUE THREAD

**Issue by azonenberg** [azonenberg/scopehal-apps#277]
glewInit returns GLEW_ERROR_NO_GLX_DISPLAY. Seems like something is looking for GLX when we're using Wayland and things bork.

**Comment by xzcvczx** [comment]
GDK_BACKEND="x11" seems to work if you have xwayland

**Comment by azonenberg** [comment]
Do we have a working flow for getting glscopeclient to run under Wayland, perhaps using xwayland? If so, please submit a PR to scopehal-docs with instructions on how to get this working.

Keeping this issue open and tagged for the v1.0 release because I want better native Wayland compatibility long term.

**Comment by dannas** [comment]
Over at the GLEW repo, https://github.com/nigels-com/glew/issues/172, the supertux folks reports that GLEW seems to be usable even if `glewInit` returns GLEW_ERROR_NO_GLX_DISPLAY.

I can start glscopeclient and display the waveforms for the demo device, if I make this modification:

```
diff --git a/src/glscopeclient/WaveformArea.cpp b/src/glscopeclient/WaveformArea.cpp
index e68601b..d8dfc09 100644
--- a/src/glscopeclient/WaveformArea.cpp
+++ b/src/glscopeclient/WaveformArea.cpp
@@ -504,7 +504,7 @@ void WaveformArea::on_realize()
 
                //Initialize GLEW
                GLenum glewResult = glewInit();
-               if (glewResult != GLEW_OK)
+        if (glewResult != GLEW_OK && glewResult != 4)
                {
                        string err =
                                "glscopeclient was unable to initialize GLEW and cannot continue.\n"
```
The Glew maintainer said that he would expose  `glewContextInit` in the public API which would allow for both EGL and GLX to be used (if I understood him correctly). But that was back in 2018 and no such change has been committed.

I guess we can use the glew-patch that supertux uses: https://github.com/supertuxkart/stk-code/commit/961ac4d79eda230722d270bbf46f1545b324d0c8, but then we'd have to package our own version of glew.

Or we can check for  $XDG_SESSION_TYPE == wayland and in that case ignore GLEW_ERROR_NO_GLX_DISPLAY? I'll google a bit to check what is the most reliable way of detecting if a program is running under wayland.
