### ISSUE TITLE
File I/O support

### ISSUE THREAD

**Issue by azonenberg** [azonenberg/scopehal-apps#3]
We should support both old-school CSV as an interchange format and a protobuf-based (?) native serialization format.

File format design is nontrivial because channels may be sparse, have different sampling rates, etc. We should also save protocol decoder config in some way.

**Comment by bvernoux** [comment]
Why not using something "standard" like sigrok file format for in/out and decoders ?
* See https://www.sigrok.org/wiki/Input_output_formats
* See https://sigrok.org/wiki/Protocol_decoders
