### ISSUE TITLE
SPDIF TOSLINK scope capture

### ISSUE THREAD

**Issue by tomverbeure** [azonenberg/scopehal-apps#315]
In response to [this tweet](https://twitter.com/azonenberg/status/1381291978696978434?s=20):

SPDIF scope capture at the pins of an TOSLINK receiver of a 1kHz audio test signal.

[spdif_1khz_2M.csv.gz](https://github.com/azonenberg/scopehal-apps/files/6337627/spdif_1khz_2M.csv.gz)

**Comment by azonenberg** [comment]
Thanks! Linked the attached data to https://github.com/azonenberg/scopehal/issues/289 which is the ticket for S/PDIF decode. Closing this ticket to avoid duplicates.
