### ISSUE TITLE
Trigger Position in time only updates when time ribbon is moved

### ISSUE THREAD

**Issue by mubes** [azonenberg/scopehal-apps#331]
The trigger position can be updated from data in the wavedesc (m_triggerOffset) but when it is the position in the time ribbon doesn't move until you drag the time ribbon left or right. It doesn't indicate the correct channel either if this has been updated on the scope and the data invalidated.

**Comment by azonenberg** [comment]
Easiest fix for this is for arrival of a new waveform to force a redraw of the time bar.

**Comment by mubes** [comment]
At the moment it doesn't....that's how I found it because I update the
trigger position from the wavedesc on each reception....not the channel
though, that has to be done with an explicit query.
