### ISSUE TITLE
Add support for "dense" waveform storage format (no explicit offset/len) to reduce size of analog captures

### ISSUE THREAD

**Issue by azonenberg** [azonenberg/scopehal-apps#92]
The current sparse file format is wasteful for non-sparse waveforms. It compresses well but it's probably worth a bit of CPU time to figure out which format to use for a given waveform to save storage space / network BW.

**Comment by bvernoux** [comment]
I would recommend https://github.com/atomicobject/heatshrink it is a must have for embedded stuff and real-time stream compression with low memory usage ...
